function pageLayout(title::String)
        return """
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    
    <% Stipple.sesstoken() %>
    <title>$title</title>
    <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "css", "genieapp.css")) %>
    <link rel='stylesheet' href='/css/genieapp.css'>
    <% else %>
    <% end %>
    <style>
      ._genie_logo {
        background:url('https://genieframework.com/logos/genie/logo-simple-with-padding.svg') no-repeat;
        background-size:40px;
        padding-top:22px;
        padding-right:10px;
        color:transparent !important;
        font-size:9pt;
      }
      ._genie .row .col-12 { width:50%; margin:auto; }
      [v-cloak] { display: none; }
    </style>
	<link rel="icon" type="image/jpg" sizes="32x32" href="/fav.jpg">
        <!-- Including mathjax script for latex typesetting -->
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/default.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/julia.min.js"></script>
  </head>
  <body>
    <div class='container'>
      <div class='row'>
        <div class='col-12'>
          <% Stipple.page(model, partial = true, v__cloak = true, [Stipple.Genie.Renderer.Html.@yield], Stipple.@if(:isready); core_theme = true) %>
        </div>
      </div>
    </div>
    <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "js", "genieapp.js")) %>
    <script src='/js/genieapp.js'></script>
    <% else %>
    <% end %>
    <footer class='_genie container'>
      <div class='row'>
        <div class='col-12'>
          <p class='text-muted credit' style='text-align:center;color:#8d99ae;'>Built with
            <a href='https://genieframework.com' target='_blank' class='_genie_logo' ref='nofollow'>Genie</a>
          </p>
        <script>hljs.highlightAll();</script>
        </div>
      </div>
    </footer>
    <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "css", "autogenerated.css")) %>
    <link rel='stylesheet' href='/css/autogenerated.css'>
    <% else %>
    <% end %>
        <script>
    // Highlight only unhighlighted code blocks when the DOM changes
    if (window.hljs) {
        function highlightNewBlocks() {
            const md_blocks = document.getElementsByTagName("md-block");
            //alert('Found' + md_blocks.length + ' markdown blocks');
            for (let i=0; i < md_blocks.length; i++) {
                //alert("Found the container again");
                let container = md_blocks[i];
                container.querySelectorAll('pre code').forEach(block => {

                    if (!block.classList.contains('hljs')) {
                        //alert("Found a code block");
                        alert(
                            'className: ' + block.className +
                            ' tagName: ' + block.tagName +
                            ' textContent: ' + block.textContent +
                            ' parent tag: ' + (block.parentElement ? block.parentElement.tagName : 'none') +
                            ' id: ' + block.id
                        );
                        hljs.highlightElement(block);
                    }
                });
            }
        }
        // Initial highlight
        highlightNewBlocks();
        // Observe DOM changes in Genie/Stipple main app container
        const containers = document.getElementsByClassName('container');
        for (let j=0; j < containers.length; j++) {
            //alert("Found a container");
            let container = containers[j];
            const observer = new MutationObserver(highlightNewBlocks);
            observer.observe(container, { childList: true, subtree: true });
        }
    }
    </script>
  </body>
</html>
"""

end
